# This is a basic workflow to help you get started with Actions

name: CI-Docutec

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build project
        run: yarn install && yarn run export

      - name: Heroku Action
        # You may pin to the exact commit or the version.
        # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
        uses: CDNievas/heroku-action@v1.0
        with:
          # Used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: 8d177cd6-0010-4a9b-8a80-18262a0ef5db
          # Email from Heroku Account
          heroku_email: marcelo.docutec@gmail.com
          # The appname to use for deploying/updating
          heroku_app_name: docutec
          # The branch that you would like to deploy to Heroku
          branch: master
          # Set this to true if want to use --force
          # useforce: # optional
          # Set if your app is located in a subdirectory.
          appdir: /out
          # Contents of the Procfile to save and deploy
          # procfile: # optional, default is 
          # Set to true if you need upload files generated dynamically by the GitHub Action to Heroku
          # dynamicFiles: # optional
          # Buildpacks to install on Heroku
          # buildpacks: # optional, default is 
          # Path to an localized env file
          # env_file: # optional, default is 
